name: Validate SAM Template

on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.13"
      - uses: aws-actions/setup-sam@v2
        with:
          use-installer: true
      - run: sam validate
